/*
 Copyright (C) 2026 Kristian Duske

 This file is part of TrenchBroom.

 TrenchBroom is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 TrenchBroom is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with TrenchBroom. If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include "kd/reflection_decl.h"

#include "vm/bbox.h"
#include "vm/ray.h"
#include "vm/vec.h"

#include <cstddef>
#include <optional>
#include <string>
#include <vector>

namespace tb::mdl
{

/** The sculpting operation applied by the terrain tool's brush. */
enum class TerrainSculptMode
{
  Raise,
  Lower,
  Flatten,
  Smooth,
};

/** The largest number of cells a terrain may have, to keep the number of generated
 * brushes manageable (every cell becomes six tetrahedra). */
constexpr size_t TerrainMaxCells = 4096;

constexpr double TerrainMinThickness = 1.0;

/**
 * A height field terrain: a regular grid of cells spanning the rectangle from the
 * terrain's origin, where every grid vertex carries a height. The solid geometry is
 * generated by extruding each cell from the base plane (the origin's Z coordinate) up
 * to its four corner heights; see TerrainBrushes.
 *
 * Vertex heights are absolute world Z coordinates. There are (columns + 1) *
 * (rows + 1) vertices, stored row by row, and columns * rows cell materials.
 */
struct Terrain
{
  /** The minimum corner of the terrain: its XY origin and the base plane's Z. */
  vm::vec3d origin;
  double cellSize = 32.0;
  size_t columns = 0;
  size_t rows = 0;

  /** Absolute Z coordinate per grid vertex, (columns + 1) * (rows + 1) entries. */
  std::vector<double> heights;
  /** Material name per cell, columns * rows entries. Empty entries fall back to the
   * default material. */
  std::vector<std::string> materials;

  std::string defaultMaterial;
  float texScaleX = 1.0f;
  float texScaleY = 1.0f;

  kdl_reflect_decl(
    Terrain,
    origin,
    cellSize,
    columns,
    rows,
    heights,
    materials,
    defaultMaterial,
    texScaleX,
    texScaleY);
};

/**
 * Creates a terrain covering the given bounds. The cells are laid out with the given
 * cell size, and every vertex starts at the bounds' maximum Z, so the terrain starts
 * out as a solid box. Returns nullopt if the bounds are too small for a single cell or
 * would need more than TerrainMaxCells cells.
 */
std::optional<Terrain> createTerrain(
  const vm::bbox3d& bounds, double cellSize, std::string defaultMaterial);

/** Whether the terrain has at least one cell and a matching number of heights. */
bool isValidTerrain(const Terrain& terrain);

size_t terrainVertexCount(const Terrain& terrain);
size_t terrainCellCount(const Terrain& terrain);

/** The index of the grid vertex in the given column and row. */
size_t terrainVertexIndex(const Terrain& terrain, size_t column, size_t row);

/** The world position of the grid vertex in the given column and row. */
vm::vec3d terrainVertexPosition(const Terrain& terrain, size_t column, size_t row);

/** The bounds enclosing the terrain's solid geometry. */
vm::bbox3d terrainBounds(const Terrain& terrain);

/**
 * Reshapes the terrain to fill the given bounds.
 *
 * The footprint keeps the terrain's cell size, so the number of columns and rows follows
 * the new size rather than the cells being stretched, and the heights are resampled
 * bilinearly from the old ones. Scaling in Z maps the old height range onto the new
 * one. The terrain's shape is therefore stretched or squashed with the bounds instead of
 * being cropped or reset.
 *
 * Returns false, leaving the terrain unchanged, if the bounds are too small for a single
 * cell or thin enough to collapse the terrain, or would need more than TerrainMaxCells
 * cells.
 */
bool scaleTerrain(Terrain& terrain, const vm::bbox3d& bounds);

/**
 * Applies one step of the sculpting brush centered at the given world position.
 *
 * Vertices within the radius are moved with a smooth (cosine) falloff towards the
 * radius: Raise and Lower move them up and down by the given strength, Flatten pulls
 * them towards the height at the brush's center, and Smooth averages them with their
 * neighbours. Only the XY distance to the brush center matters, so the brush behaves
 * like a cylinder.
 *
 * Returns whether any vertex was changed.
 */
bool sculptTerrain(
  Terrain& terrain,
  const vm::vec3d& center,
  double radius,
  double strength,
  TerrainSculptMode mode);

/**
 * Assigns the given material to every cell whose center lies within the radius of the
 * given world position. Returns whether any cell was changed.
 */
bool paintTerrain(
  Terrain& terrain,
  const vm::vec3d& center,
  double radius,
  const std::string& materialName);

/** The material of the cell in the given column and row, or the default material. */
const std::string& terrainCellMaterial(const Terrain& terrain, size_t column, size_t row);

/**
 * Returns the point where the given ray enters the terrain's surface, or nullopt if it
 * does not hit it. The surface is the triangulated top of the height field.
 */
std::optional<vm::vec3d> pickTerrain(const Terrain& terrain, const vm::ray3d& ray);

} // namespace tb::mdl
